env:
  browser: true
  commonjs: true
  es2021: true
extends: standard
overrides: []
parserOptions:
  ecmaVersion: latest
rules:
  semi: ["error", "always"]
  quotes: ["error", "double"]
  space-before-function-paren: 0
